import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

export type DesignMdOverride = {
  role?: string;
  description?: string;
};

export function updateDesignMd(
  workspaceRoot: string,
  componentId: string,
  data: DesignMdOverride,
): void {
  const designMdPath = join(workspaceRoot, "DESIGN.md");
  let content = "";

  if (existsSync(designMdPath)) {
    content = readFileSync(designMdPath, "utf-8");
  } else {
    const projectName = workspaceRoot.split(/[/\\]/).pop() || "Project";
    content = `# ${projectName} Design System\n\nGenerated by BlockSmith. Finalized component rules will appear below.\n\n`;
  }

  const componentHeadingRe = new RegExp(`^##\\s+${componentId}\\s*$`, "im");
  const match = content.match(componentHeadingRe);
  const titleCaseId =
    componentId.charAt(0).toUpperCase() + componentId.slice(1);
  const newSection = `## ${titleCaseId}\n\n**Role:** ${data.role || "TBD"}\n\n${data.description || ""}\n\n<!-- blocksmith-end-${componentId} -->\n`;

  if (match) {
    const startIndex = match.index!;
    const afterHeading = content.substring(startIndex + match[0].length);
    const endMarkerRe = new RegExp(
      `^<!--\\s*blocksmith-end-${componentId}\\s*-->`,
      "m",
    );
    const endMarkerMatch = afterHeading.match(endMarkerRe);

    let endIndex = startIndex + match[0].length;
    if (endMarkerMatch) {
      endIndex += endMarkerMatch.index! + endMarkerMatch[0].length;
    } else {
      const nextHeadingMatch = afterHeading.match(/^##\s+/m);
      if (nextHeadingMatch) {
        endIndex += nextHeadingMatch.index!;
      } else {
        endIndex = content.length;
      }
    }

    const before = content.substring(0, startIndex);
    const after = content.substring(endIndex).replace(/^\n+/, "\n\n");
    content = `${before}${newSection}${after}`;
  } else {
    content = content.replace(/\n+$/, "") + `\n\n${newSection}`;
  }

  writeFileSync(designMdPath, content, "utf-8");
}

/**
 * Write the full design-system markdown to DESIGN.md (overwrites). BlockSmith
 * owns this file as generated output — it is the complete wiki export with
 * promoted governance merged in, not a per-component delta.
 */
export function writeDesignMd(workspaceRoot: string, markdown: string): string {
  const designMdPath = join(workspaceRoot, "DESIGN.md");
  const body = markdown.endsWith("\n") ? markdown : `${markdown}\n`;
  writeFileSync(designMdPath, body, "utf-8");
  return designMdPath;
}

/**
 * Write blocksmith.lock at the repo root so CI and agents resolve the exact
 * block versions a human promoted in the wiki.
 */
export function writeLock(workspaceRoot: string, lock: unknown): string {
  const lockPath = join(workspaceRoot, "blocksmith.lock");
  writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`, "utf-8");
  return lockPath;
}

export function updateWikiOverrides(
  workspaceRoot: string,
  overridesMap: Record<string, DesignMdOverride>,
): void {
  const dir = join(workspaceRoot, ".blocksmith");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const path = join(dir, "wiki-overrides.json");
  let overrides: {
    version: 1;
    components: Record<string, DesignMdOverride & { updatedAt?: string }>;
  } = { version: 1, components: {} };

  if (existsSync(path)) {
    try {
      const raw = JSON.parse(readFileSync(path, "utf-8"));
      if (raw?.version === 1 && raw.components) overrides = raw;
    } catch {
      /* fresh */
    }
  }

  for (const [id, data] of Object.entries(overridesMap)) {
    overrides.components[id] = {
      ...data,
      updatedAt: new Date().toISOString(),
    };
  }

  writeFileSync(path, `${JSON.stringify(overrides, null, 2)}\n`, "utf-8");
}
