import type { ComponentDoc, DesignSystem } from "@/lib/blocks/types";
import type { DesignIR } from "@/lib/design-ir/schema";
import {
  componentSpecToCss,
  parseComponentPreviewSpec,
  type ComponentPreviewContext,
} from "@/ai-lab/04-component-previews";
import type {
  DashboardModel,
  DemoCta,
  DemoModel,
  LandingModel,
} from "@/ai-lab/06-demo-compose";

/**
 * Phase 3 — code export.
 *
 * Because the demo is composed deterministically from the IR + components, the
 * emitted code is faithful *by construction*: token CSS comes straight from the
 * compiled chrome, component classes from the same parsed specs the preview
 * uses, and the page markup from the validated DemoPageModel. No hallucinated
 * values can appear — there is no model in this path.
 */

export type CodeFile = {
  path: string;
  language: "css" | "tsx";
  contents: string;
};

const HEADER = "/* Generated by BlockSmith — faithful to your design system. */";

function cssBlock(title: string, entries: [string, string][]): string {
  if (entries.length === 0) return "";
  const lines = entries.map(([k, v]) => `  ${k}: ${v};`).join("\n");
  return `  /* ${title} */\n${lines}`;
}

export function generateTokenCss(ir: DesignIR): string {
  const colors = Object.entries(ir.colorVariables);
  const fonts = Object.entries(ir.fontStacks);
  const chrome = Object.entries(ir.wikiChrome.cssVariables).filter(
    ([k]) => !ir.fontStacks[k],
  );

  const blocks = [
    cssBlock("Color tokens", colors),
    cssBlock("Typography", fonts),
    cssBlock("Theme / chrome", chrome),
  ].filter(Boolean);

  return `${HEADER}\n:root {\n${blocks.join("\n\n")}\n}\n`;
}

export function generateComponentCss(
  system: DesignSystem,
  ctx: ComponentPreviewContext,
): string {
  const rules = system.components.map((c: ComponentDoc) => {
    const spec = parseComponentPreviewSpec(c, ctx);
    return componentSpecToCss(spec, `.ds-${c.id}`);
  });
  return `${HEADER}\n\n${rules.join("\n\n")}\n`;
}

const LANDING_LAYOUT_CSS = `${HEADER}

.ds-demo {
  background: var(--wiki-bg);
  color: var(--wiki-text);
  font-family: var(--wiki-font);
}
.ds-nav {
  display: flex; align-items: center; justify-content: space-between;
  padding: 20px 32px;
  border-bottom: var(--wiki-nav-divider, 1px solid var(--wiki-border));
}
.ds-brand { font-family: var(--wiki-display-font); font-weight: 700; font-size: 18px; }
.ds-nav__links { display: flex; gap: 28px; }
.ds-nav__links span { color: var(--wiki-muted); font-size: 14px; }
.ds-hero { padding: 80px 32px; text-align: center; }
.ds-hero__eyebrow {
  text-transform: uppercase; letter-spacing: 0.18em; font-size: 12px;
  font-weight: 600; color: var(--wiki-accent); margin-bottom: 16px;
}
.ds-hero__title {
  font-family: var(--wiki-display-font); font-size: 48px; font-weight: 700;
  line-height: 1.05; letter-spacing: var(--wiki-heading-tracking); margin: 0 auto; max-width: 760px;
}
.ds-hero__subtitle { color: var(--wiki-muted); font-size: 18px; margin: 24px auto 0; max-width: 560px; }
.ds-hero__actions { display: flex; gap: 16px; justify-content: center; margin-top: 36px; }
.ds-features { padding: 0 32px 80px; }
.ds-features__heading { font-family: var(--wiki-display-font); font-size: 24px; text-align: center; margin-bottom: 40px; }
.ds-grid { display: grid; gap: 20px; max-width: 960px; margin: 0 auto; grid-template-columns: repeat(3, 1fr); }
.ds-card {
  background: var(--wiki-sidebar); padding: 24px;
  border: var(--wiki-card-border, 1px solid var(--wiki-border));
  border-radius: var(--wiki-radius-card); box-shadow: var(--wiki-card-shadow, none);
}
.ds-card__title { font-weight: 600; }
.ds-card__body { color: var(--wiki-muted); font-size: 14px; margin-top: 8px; }
.ds-cta-band { padding: 64px 32px; text-align: center; background: var(--wiki-accent); color: var(--wiki-cta-on-accent); }
.ds-footer { padding: 32px; text-align: center; font-size: 12px; color: var(--wiki-muted); border-top: 1px solid var(--wiki-border); }

@media (max-width: 720px) { .ds-grid { grid-template-columns: 1fr; } .ds-nav__links { display: none; } }
`;

function escapeJsx(text: string): string {
  return text.replace(/[{}<>]/g, (m) => ({ "{": "&#123;", "}": "&#125;", "<": "&lt;", ">": "&gt;" }[m]!));
}

function ctaJsx(cta: DemoCta, extraClass = ""): string {
  if (!cta) return "";
  return `<button type="button" className="ds-${cta.id}${extraClass ? ` ${extraClass}` : ""}">${escapeJsx(cta.label)}</button>`;
}

export function generateLandingTsx(model: LandingModel): string {
  const links = model.navLinks
    .map((l) => `          <span>${escapeJsx(l)}</span>`)
    .join("\n");

  const features = model.features.items
    .map(
      (f) => `          <div className="ds-card">
            <p className="ds-card__title">${escapeJsx(f.title)}</p>
            <p className="ds-card__body">${escapeJsx(f.body)}</p>
          </div>`,
    )
    .join("\n");

  return `${HEADER.replace("/*", "//").replace("*/", "")}
import "./tokens.css";
import "./components.css";
import "./styles.css";

export function LandingPage() {
  return (
    <div className="ds-demo">
      <nav className="ds-nav">
        <span className="ds-brand">${escapeJsx(model.brandName)}</span>
        <div className="ds-nav__links">
${links}
        </div>
        ${ctaJsx(model.navCta)}
      </nav>

      <header className="ds-hero">
        ${model.hero.eyebrow ? `<p className="ds-hero__eyebrow">${escapeJsx(model.hero.eyebrow)}</p>` : ""}
        <h1 className="ds-hero__title">${escapeJsx(model.hero.title)}</h1>
        <p className="ds-hero__subtitle">${escapeJsx(model.hero.subtitle)}</p>
        <div className="ds-hero__actions">
          ${ctaJsx(model.hero.primary)}
          ${ctaJsx(model.hero.secondary)}
        </div>
      </header>

      <section className="ds-features">
        <h2 className="ds-features__heading">${escapeJsx(model.features.heading)}</h2>
        <div className="ds-grid">
${features}
        </div>
      </section>

      <section className="ds-cta-band">
        <h2>${escapeJsx(model.closing.title)}</h2>
        <p>${escapeJsx(model.closing.subtitle)}</p>
        ${ctaJsx(model.closing.action)}
      </section>

      <footer className="ds-footer">${escapeJsx(model.footerNote)}</footer>
    </div>
  );
}
`;
}

const DASHBOARD_LAYOUT_CSS = `${HEADER}

.ds-app { display: flex; min-height: 520px; background: var(--wiki-bg); color: var(--wiki-text); font-family: var(--wiki-font); }
.ds-side { width: 208px; flex: none; padding: 16px; background: var(--wiki-sidebar); border-right: 1px solid var(--wiki-border); }
.ds-side__brand { display: block; font-family: var(--wiki-display-font); font-weight: 700; font-size: 16px; padding: 0 8px; margin-bottom: 24px; }
.ds-side__item { padding: 8px 12px; border-radius: 8px; font-size: 14px; color: var(--wiki-muted); }
.ds-side__item--active { background: var(--wiki-active); color: var(--wiki-text); font-weight: 600; }
.ds-main { flex: 1; min-width: 0; }
.ds-topbar { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 16px 24px; border-bottom: 1px solid var(--wiki-border); }
.ds-search { max-width: 320px; width: 100%; padding: 8px 14px; font-size: 14px; background: var(--wiki-bg); color: var(--wiki-text); border: 1px solid var(--wiki-border); border-radius: var(--wiki-radius); }
.ds-stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; padding: 24px 24px 0; }
.ds-stat { padding: 16px; background: var(--wiki-sidebar); border: var(--wiki-card-border, 1px solid var(--wiki-border)); border-radius: var(--wiki-radius-card); }
.ds-stat__label { font-size: 12px; color: var(--wiki-muted); }
.ds-stat__value { font-family: var(--wiki-display-font); font-size: 24px; font-weight: 700; }
.ds-stat__delta { font-size: 12px; font-weight: 600; color: var(--wiki-accent); margin-left: 8px; }
.ds-table-wrap { margin: 24px; border: 1px solid var(--wiki-border); border-radius: var(--wiki-radius-card); overflow: hidden; }
.ds-table-title { padding: 12px 20px; font-weight: 600; font-size: 14px; background: var(--wiki-sidebar); border-bottom: 1px solid var(--wiki-border); }
.ds-table { width: 100%; font-size: 14px; border-collapse: collapse; }
.ds-table th { text-align: left; padding: 8px 20px; font-size: 12px; text-transform: uppercase; color: var(--wiki-muted); }
.ds-table td { padding: 12px 20px; border-top: 1px solid var(--wiki-border); }

@media (max-width: 720px) { .ds-side { display: none; } .ds-stats { grid-template-columns: repeat(2, 1fr); } }
`;

export function generateDashboardTsx(model: DashboardModel): string {
  const nav = model.navItems
    .map(
      (n) =>
        `          <div className="ds-side__item${n.active ? " ds-side__item--active" : ""}">${escapeJsx(n.label)}</div>`,
    )
    .join("\n");

  const stats = model.stats
    .map(
      (s) => `          <div className="ds-stat">
            <p className="ds-stat__label">${escapeJsx(s.label)}</p>
            <p><span className="ds-stat__value">${escapeJsx(s.value)}</span><span className="ds-stat__delta">${escapeJsx(s.delta)}</span></p>
          </div>`,
    )
    .join("\n");

  const cols = model.table.columns
    .map((c) => `<th>${escapeJsx(c)}</th>`)
    .join("");
  const rows = model.table.rows
    .map((r) => {
      const cells = r.cells.map((c) => `<td>${escapeJsx(c)}</td>`).join("");
      const badge = model.tagSpec ? `ds-${model.tagSpec.kind}` : "ds-badge";
      return `            <tr>${cells}<td><span className="${badge}">${escapeJsx(r.status)}</span></td></tr>`;
    })
    .join("\n");

  return `${HEADER.replace("/*", "//").replace("*/", "")}
import "./tokens.css";
import "./components.css";
import "./styles.css";

export function DashboardPage() {
  return (
    <div className="ds-app">
      <aside className="ds-side">
        <span className="ds-side__brand">${escapeJsx(model.brandName)}</span>
${nav}
      </aside>
      <div className="ds-main">
        <header className="ds-topbar">
          <input className="ds-search" placeholder="${escapeJsx(model.searchPlaceholder)}" readOnly />
          <div>${ctaJsx(model.topbarCta)} ${ctaJsx(model.primaryAction)}</div>
        </header>
        <div className="ds-stats">
${stats}
        </div>
        <div className="ds-table-wrap">
          <div className="ds-table-title">${escapeJsx(model.table.title)}</div>
          <table className="ds-table">
            <thead><tr>${cols}<th>Status</th></tr></thead>
            <tbody>
${rows}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
`;
}

export function generateProjectFiles(
  system: DesignSystem,
  ir: DesignIR,
  ctx: ComponentPreviewContext,
  model: DemoModel,
): CodeFile[] {
  const shared: CodeFile[] = [
    { path: "tokens.css", language: "css", contents: generateTokenCss(ir) },
    {
      path: "components.css",
      language: "css",
      contents: generateComponentCss(system, ctx),
    },
  ];

  if (model.archetype === "dashboard") {
    return [
      ...shared,
      { path: "styles.css", language: "css", contents: DASHBOARD_LAYOUT_CSS },
      { path: "DashboardPage.tsx", language: "tsx", contents: generateDashboardTsx(model) },
    ];
  }

  return [
    ...shared,
    { path: "styles.css", language: "css", contents: LANDING_LAYOUT_CSS },
    { path: "LandingPage.tsx", language: "tsx", contents: generateLandingTsx(model) },
  ];
}
