import { existsSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

/** Updates or creates a `## Component` section in DESIGN.md (Goal 2 writeback). */
export function updateDesignMd(
  workspaceRoot: string,
  componentId: string,
  data: { role?: string; description?: string },
): void {
  const designMdPath = join(workspaceRoot, "DESIGN.md");
  let content = "";

  if (existsSync(designMdPath)) {
    content = readFileSync(designMdPath, "utf-8");
  } else {
    const projectName = workspaceRoot.split(/[/\\]/).pop() || "Project";
    content = `# ${projectName} Design System\n\nGenerated by BlockSmith. Finalized component rules will appear below.\n\n`;
  }

  const componentHeadingRe = new RegExp(`^##\\s+${componentId}\\s*$`, "im");
  const match = content.match(componentHeadingRe);
  const titleCaseId =
    componentId.charAt(0).toUpperCase() + componentId.slice(1);
  const newSection = `## ${titleCaseId}\n\n**Role:** ${data.role || "TBD"}\n\n${data.description || ""}\n\n<!-- blocksmith-end-${componentId} -->\n`;

  if (match) {
    const startIndex = match.index!;
    const afterHeading = content.substring(startIndex + match[0].length);
    const endMarkerRe = new RegExp(
      `^<!--\\s*blocksmith-end-${componentId}\\s*-->`,
      "m",
    );
    const endMarkerMatch = afterHeading.match(endMarkerRe);

    let endIndex = startIndex + match[0].length;
    if (endMarkerMatch) {
      endIndex += endMarkerMatch.index! + endMarkerMatch[0].length;
    } else {
      const nextHeadingMatch = afterHeading.match(/^##\s+/m);
      if (nextHeadingMatch) {
        endIndex += nextHeadingMatch.index!;
      } else {
        endIndex = content.length;
      }
    }

    const before = content.substring(0, startIndex);
    const after = content.substring(endIndex).replace(/^\n+/, "\n\n");
    content = `${before}${newSection}${after}`;
  } else {
    content = content.replace(/\n+$/, "") + `\n\n${newSection}`;
  }

  writeFileSync(designMdPath, content, "utf-8");
}
