/** @deprecated Import from `@/components/icons` */
export {
  IconArrowRight,
  IconArrowUp,
  IconBrightness,
  IconCheck,
  IconCog,
  IconColorPalette,
  IconDarkMode,
  IconDelete,
  IconDownload,
  IconExpand,
  IconLayout,
  IconLink,
  IconLock,
  IconModule,
  IconModuleAlt,
  IconNewspaper,
  IconPaperclip,
  IconSearch,
  IconUpload,
  IconBlockType,
  BLOCK_TYPE_ICON,
  type StreamlineIconProps,
} from "@/components/icons";
